---
- name: Run "apt-get update"
  apt:
    update_cache: yes

- name: Run "apt-get dist-upgrade"
  apt:
    upgrade: dist

- name: Check if reboot is required.
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- debug:
    msg: "Reboot is required!!!"
  when: reboot_required.stat.exists

- name: Rebooting host!
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: reboot_required.stat.exists and reboot_ok

- name: Wait for the reboot...
  wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 300
  when: reboot_required.stat.exists and reboot_ok 

- name: Run "apt-get autoremove"
  apt:
    autoremove: yes



