#---------------------------------------------#
# Author: Adam WezvaTechnologies
# Call/Whatsapp: +91-9739110917
#---------------------------------------------#

# Define valid Jenkins version and repo in your vars file or top of playbook
vars:
  java: openjdk-17-jdk
  jenkins_repo: https://pkg.jenkins.io/debian-stable
  jenkins_version: 2.440.1  # Make sure this version is valid (run `apt-cache madison jenkins` to check)

# Ensure Jenkins GPG key is added
- name: Ensure the Jenkins APT repository key is installed
  get_url:
    url: "{{ jenkins_repo }}/jenkins.io-2023.key"
    dest: /usr/share/keyrings/jenkins-keyring.asc

# Add the Jenkins repo
- name: Ensure the Jenkins repository is configured
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] {{ jenkins_repo }} binary/"
    state: present
    filename: jenkins

# Update APT cache after adding repo
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

# Install Java & dependencies
- name: Install Java, fontconfig, and NFS packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ java }}"
    - fontconfig
    - nfs-common
    - mount

# Install specific Jenkins version
- name: Ensure specific Jenkins version is installed
  apt:
    name: "jenkins={{ jenkins_version }}"
    state: present



# - name: Ensure EFS entry exists in /etc/fstab
#   mount:
#     path: /var/lib/jenkins
#     src: "{{efs}}.efs.ap-south-1.amazonaws.com:/"
#     fstype: nfs4
#     opts: "_netdev"
#     state: mounted

- name: echo efs
  command: echo "efs"
  
- name: Ensure EFS entry exists in /var/lib/jenkins
  command: sudo mount -t nfs4 -o nfsvers=4.1 {{efs}}.efs.ap-south-1.amazonaws.com:/ /var/lib/jenkins/

- name: Ensure EFS entry exists in /etc/fstab
  mount:
    path: /var/lib/jenkins
    src: "{{efs}}.efs.ap-south-1.amazonaws.com:/"
    fstype: nfs4
    opts: "_netdev"
    state: mounted

- name: Ensure EFS entry exists in /etc/fstab
  mount:
    path: /var/lib/jenkins
    src: "{{efs}}.efs.ap-south-1.amazonaws.com:/"
    fstype: nfs4
    opts: "_netdev"
    state: present

- name: Change permission back to Jenkins user
  file:
    path: /var/lib/jenkins
    owner: jenkins
    group: jenkins
    state: directory
    recurse: yes

- name: Mount all file systems from fstab
  command: mount -a
  when: ansible_mounts | selectattr('mount', '==', '/var/lib/jenkins') | list | length == 0

- name: Check if port 8080 is listening
  wait_for:
    port: 8080
    timeout: 180
    msg: "Timeout waiting for 8080 to respond"
  register: port_check
  ignore_errors: yes

- name: Print message if Jenkins is not running
  debug:
    msg: "*== Jenkins NOT Running ==*"
  when: port_check.failed == true

#---------------------------------------------#
# Author: Adam WezvaTechnologies
# Call/Whatsapp: +91-9739110917
#---------------------------------------------#
